export const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const catalog=[
 {id:'horizontal',name:'横向滑动相册',icon:'▧',group:'交互',level:'需真机预览',desc:'一屏一张，滑动翻阅你的视觉切片。'},
 {id:'vertical',name:'纵向滚动长图',icon:'↕',group:'交互',level:'需真机预览',desc:'固定窗口里的长图漫游。'},
 {id:'carousel',name:'自动循环轮播',icon:'⟳',group:'动画',level:'SVG 实验',desc:'用 SVG 时间轴循环播放图片，不依赖 JavaScript。'},
 {id:'reveal',name:'点击揭幕',icon:'◈',group:'交互',level:'SVG 实验',desc:'点击封面，揭开下面的图片。'},
 {id:'parallax',name:'透视叠层长图',icon:'▱',group:'交互',level:'实验 · 设备差异',desc:'参考推文中的 perspective + rotateX 叠层结构。'},
 {id:'marquee',name:'滚动字幕',icon:'⇢',group:'动画',level:'SVG 实验',desc:'让一句宣言穿过画面。'},
 {id:'record',name:'黑胶唱片',icon:'◉',group:'动画',level:'SVG 实验',desc:'缓慢转动的唱片，与声音一起呼吸。'},
 {id:'equalizer',name:'律动频谱',icon:'▥',group:'动画',level:'SVG 实验',desc:'可调速度的装饰频谱，不读取音乐音量。'},
 {id:'neon',name:'霓虹标题',icon:'✳',group:'排版',level:'内联样式',desc:'荧光文字、暗色背景和细节编号。'},
 {id:'terminal',name:'复古终端',icon:'⌘',group:'排版',level:'内联样式',desc:'一扇留给文字的复古系统窗口。'},
 {id:'ticket',name:'演出票根',icon:'⊞',group:'排版',level:'内联样式',desc:'票根式信息卡，适合演出与活动。'},
 {id:'divider',name:'信号分隔线',icon:'⌁',group:'排版',level:'内联样式',desc:'频率、编号与留白，分隔一篇长文。'},
 {id:'music',name:'原生音乐装饰',icon:'♫',group:'音乐',level:'需要原生卡片',desc:'使用正文中已有的微信原生音频/音乐卡片。'},
 {id:'custom',name:'自定义 HTML',icon:'</>',group:'源码',level:'自动清理',desc:'粘贴 HTML，保留内联样式与 SVG，移除脚本。'}
];
const num=(v,min,max,d)=>Math.min(max,Math.max(min,Number(v)||d));
const color=(v,d)=>/^#[0-9a-f]{6}$/i.test(v||'')?v:d;
export function isWechatImage(url){try{const u=new URL(url);return u.protocol==='https:'&&(u.hostname==='mmbiz.qpic.cn'||u.hostname==='mmbiz.qlogo.cn')}catch{return false}}
const demo=(i,c)=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 400" width="100%" height="100%"><rect width="600" height="400" fill="${['#24382e','#3b3147','#34424a'][i%3]}"/><g stroke="${c}" fill="none" opacity=".7">${Array.from({length:12},(_,j)=>`<ellipse cx="300" cy="185" rx="${50+j*18}" ry="${25+j*9}" transform="rotate(${i*30+20} 300 185)"/>`).join('')}</g><text x="28" y="45" fill="${c}" font-size="14" font-family="monospace">PAPERPLAY / VISUAL STUDY 0${i+1}</text><text x="28" y="366" fill="${c}" font-size="25" font-family="sans-serif">${['声音的形状','风经过的地方','夜晚的频率'][i%3]}</text></svg>`;
export function build(type,p={}){
 const c=color(p.accent,'#ccf58a'),bg=color(p.background,'#19251e'),w=600,h=num(p.height,80,1200,360),radius=num(p.radius,0,80,0),duration=num(p.duration,1,60,4),title=escapeHTML(p.title||'让声音，有迹可循。'),body=escapeHTML(p.body||'把瞬间收进纸间。\n把故事留给下一个听见它的人。').replace(/\n/g,'<br/>');
 const urls=String(p.urls||'').split(/\n/).map(s=>s.trim()).filter(Boolean);const pics=urls.length?urls:[null,null,null];
 const picture=(src,i,style='')=>src?`<img src="${escapeHTML(src)}" data-src="${escapeHTML(src)}" style="display:block;width:100%;height:100%;object-fit:cover;${style}"/>`:demo(i,c);
 const outer=content=>`<section style="margin:16px 0;box-sizing:border-box;overflow:hidden;border-radius:${radius}px;">${content}</section>`;
 const svg=(content,height=h)=>`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 ${w} ${height}" style="display:block;width:100%;height:auto;background:${bg};" role="img" aria-label="${title}">${content}</svg>`;
 const svgPic=(src,i,x=0)=>src?`<image x="${x}" y="0" width="600" height="${h}" xlink:href="${escapeHTML(src)}" href="${escapeHTML(src)}" preserveAspectRatio="xMidYMid slice"/>`:`<svg x="${x}" width="600" height="${h}" viewBox="0 0 600 400">${demo(i,c).replace(/^<svg[^>]*>|<\/svg>$/g,'')}</svg>`;
 if(type==='horizontal'||type==='vertical'){const vertical=type==='vertical';return outer(`<section style="width:100%;height:${h}px;overflow-${vertical?'y':'x'}:auto;overflow-${vertical?'x':'y'}:hidden;white-space:${vertical?'normal':'nowrap'};font-size:0;line-height:0;scroll-snap-type:${vertical?'y':'x'} mandatory;-webkit-overflow-scrolling:touch;">${pics.map((s,i)=>`<section style="display:${vertical?'block':'inline-block'};vertical-align:top;width:100%;height:${h}px;scroll-snap-align:start;white-space:normal;">${picture(s,i)}</section>`).join('')}</section><section style="padding:10px;text-align:center;color:${c};background:${bg};font-size:11px;letter-spacing:2px;">${vertical?'↕ 上下滚动':'← 左右滑动 →'} / ${pics.length} FRAMES</section>`)}
 if(type==='carousel'){const n=pics.length,values=pics.map((_,i)=>`${-i*600} 0`).concat('0 0').join(';');return outer(svg(`<g>${pics.map((s,i)=>svgPic(s,i,i*600)).join('')}<animateTransform attributeName="transform" type="translate" values="${values}" keyTimes="${Array.from({length:n+1},(_,i)=>i/n).join(';')}" calcMode="discrete" dur="${n*duration}s" repeatCount="indefinite"/></g>`))}
 if(type==='reveal')return outer(svg(`${svgPic(pics[0],0)}<g><rect width="600" height="${h}" fill="${bg}"/><text x="300" y="${h/2-15}" text-anchor="middle" font-size="32" fill="${c}" font-family="sans-serif">${title}</text><text x="300" y="${h/2+30}" text-anchor="middle" font-size="14" fill="${c}">点击这里 · 揭开这一页</text><animate attributeName="opacity" from="1" to="0" begin="click" dur="0.8s" fill="freeze"/></g>`));
 if(type==='parallax')return outer(`<section style="width:100%;height:${h}px;overflow:hidden auto;perspective:50px;transform-style:preserve-3d;background:${bg};"><section style="height:0;overflow:visible;transform-style:preserve-3d;padding-top:0.02px;">${pics.map((s,i)=>`<section style="margin:${i?70:0}px 0;${i%2?'transform:rotateX(14deg) scale(3) translateZ(-30px);transform-origin:center center;':''}height:${h}px;">${picture(s,i)}</section>`).join('')}</section><section style="height:${pics.length*(h+70)}px;pointer-events:none;"></section></section>`);
 if(type==='marquee')return outer(svg(`<g><text x="0" y="85" font-family="sans-serif" font-weight="700" font-size="54" fill="${c}">${title}　✳　${title}　✳　${title}</text><animateTransform attributeName="transform" type="translate" from="600 0" to="-1800 0" dur="${duration*4}s" repeatCount="indefinite"/></g>`,130));
 if(type==='record')return outer(svg(`<g><circle cx="300" cy="200" r="167" fill="#101411"/>${Array.from({length:13},(_,i)=>`<circle cx="300" cy="200" r="${65+i*8}" fill="none" stroke="#334236"/>`).join('')}<circle cx="300" cy="200" r="60" fill="${c}"/><circle cx="300" cy="200" r="8" fill="${bg}"/><path d="M300 50L310 120" stroke="${c}" stroke-width="2"/><text x="300" y="185" text-anchor="middle" fill="${bg}" font-family="monospace" font-size="12">SIDE A</text><animateTransform attributeName="transform" type="rotate" from="0 300 200" to="360 300 200" dur="${duration*3}s" repeatCount="indefinite"/></g><text x="300" y="395" text-anchor="middle" fill="${c}" font-size="16">${title}</text>`,430));
 if(type==='equalizer')return outer(svg(`${Array.from({length:28},(_,i)=>{const v=25+(i*37)%115;return `<rect x="${25+i*20}" y="${170-v}" width="11" height="${v}" rx="3" fill="${c}"><animate attributeName="height" values="${v};20;${v}" dur="${duration*(.3+i%4*.1)}s" repeatCount="indefinite"/><animate attributeName="y" values="${170-v};150;${170-v}" dur="${duration*(.3+i%4*.1)}s" repeatCount="indefinite"/></rect>`}).join('')}<text x="30" y="211" fill="${c}" font-family="monospace" font-size="13">SIGNAL / ${title}</text>`,240));
 if(type==='neon')return outer(`<section style="padding:38px 25px;background:${bg};border:1px solid ${c};"><p style="margin:0 0 20px;color:${c};font-size:11px;letter-spacing:4px;">FIELD NOTES / 001</p><p style="margin:0 0 20px;font-size:32px;font-weight:800;line-height:1.4;color:${c};text-shadow:0 0 18px ${c};">${title}</p><p style="margin:0;color:#d0d7c9;font-size:14px;line-height:1.9;">${body}</p></section>`);
 if(type==='terminal')return outer(`<section style="border:2px solid ${c};background:${bg};color:${c};font-family:monospace;"><section style="background:${c};color:${bg};padding:8px 12px;font-size:12px;">● ● ●　${title} <span style="float:right">_ □ ×</span></section><section style="padding:25px;font-size:15px;line-height:2;">&gt; SYSTEM READY<br/><br/>${body}<br/><br/>▊</section></section>`);
 if(type==='ticket')return outer(`<section style="padding:26px;background:${c};color:${bg};border:2px solid ${bg};"><p style="font-size:11px;letter-spacing:3px;margin:0 0 15px">ADMIT ONE / LIVE SESSION</p><p style="font-size:30px;font-weight:700;line-height:1.4;margin:0 0 25px;">${title}</p><section style="border-top:2px dashed ${bg};padding-top:20px;font-size:14px;line-height:1.8;">${body}</section><p style="font-family:monospace;letter-spacing:5px;font-size:24px;margin-bottom:0">║▌│█║▌│║▌║█</p></section>`);
 if(type==='divider')return outer(`<section style="display:flex;align-items:center;gap:12px;padding:18px 0;color:${c};background:${bg};"><span style="flex:1;border-top:1px solid ${c};"></span><span style="font-size:12px;letter-spacing:2px;">✳ ${title} ✳</span><span style="flex:1;border-top:1px solid ${c};"></span></section>`);
 if(type==='music')return outer(`<section style="padding:22px;background:${bg};border:1px solid ${c};color:${c};"><p style="font-size:12px;letter-spacing:3px;margin:0 0 16px">♫ NOW PLAYING</p>${p.music||`<p style="font-size:20px;">${title}</p><p style="font-size:13px;color:#9ca994;">请在公众号工具栏「音频」中插入原生卡片</p>`}<p style="font-size:12px;line-height:1.7;margin:16px 0 0;">${body}</p></section>`);
 return p.custom||'';
}
export function cleanHTML(input){
 const doc=new DOMParser().parseFromString(input,'text/html'),notes=[];
 const allowed=new Set('section div span p br strong b em i u s strike a img h1 h2 h3 h4 h5 h6 blockquote ul ol li table tbody thead tr td th hr svg g defs rect circle ellipse path line polyline polygon text tspan image use clippath mask lineargradient radialgradient stop pattern filter fegaussianblur feoffset femerge femergenode animate animatetransform animatemotion mpath set foreignobject mp-common-mpaudio mp-common-music mpvoice qqmusic'.split(' '));
 const drop=new Set('script style iframe object embed form input button textarea select link meta base audio video'.split(' '));
 const allowedAttrs=new Set('style class id title alt href xlink:href src xmlns xmlns:xlink viewbox preserveaspectratio width height x y x1 y1 x2 y2 cx cy r rx ry d points fill stroke stroke-width stroke-linecap stroke-linejoin opacity transform transform-origin offset stop-color stop-opacity clip-path mask filter font-size font-family font-weight text-anchor dominant-baseline patternunits patterntransform gradientunits gradienttransform attributename attributetype type from to by values keytimes keysplines calcmode dur begin end repeatcount repeatdur restart additive accumulate path rotate keypoints version role aria-label'.split(' '));
 for(const el of [...doc.body.querySelectorAll('*')]){
 const tag=el.localName.toLowerCase();if(drop.has(tag)){notes.push(`移除 ${tag}`);el.remove();continue}if(!allowed.has(tag)){notes.push(`展开不支持的标签 ${tag}`);el.replaceWith(...el.childNodes);continue}
 if(['animate','animatetransform','set'].includes(tag)&&!['opacity','transform','x','y','x1','x2','y1','y2','width','height','r','rx','ry','cx','cy','fill','stroke','stroke-width','stroke-dashoffset','viewBox'].includes(el.getAttribute('attributeName'))){notes.push('移除可修改非视觉属性的动画');el.remove();continue}
 for(const a of [...el.attributes]){const name=a.name.toLowerCase(),v=a.value;if(name.startsWith('on')||name==='srcdoc'||(!allowedAttrs.has(name)&&!name.startsWith('data-')&&!((tag.startsWith('mp')||tag==='qqmusic')&&/^[a-z_\d-]+$/.test(name)))){el.removeAttribute(a.name);continue}
 if(['href','xlink:href','src'].includes(name)&&!/^https:\/\//i.test(v)&&!/^#[\w-]+$/.test(v)){el.removeAttribute(a.name);notes.push('移除非 HTTPS / 非片段链接')}
 if(['fill','stroke','filter','clip-path','mask'].includes(name)&&/url\(/i.test(v)&&!/^url\(\s*['"]?#[\w-]+['"]?\s*\)$/i.test(v)){el.removeAttribute(a.name);notes.push('移除外部 SVG 引用')}
 if(name==='style'){const probe=document.createElement('span');probe.setAttribute('style',v);for(const k of [...probe.style]){const val=probe.style.getPropertyValue(k);if(/expression|javascript|@import|behavior|-moz-binding/i.test(k+val)||/url\(/i.test(val)&&!/^url\(["']?https:\/\/mmbiz\.qpic\.cn\//i.test(val)){probe.style.removeProperty(k);notes.push('移除不安全的样式')}if(['position','z-index'].includes(k)&&['fixed','sticky'].includes(val))probe.style.removeProperty(k)}el.setAttribute('style',probe.style.cssText)}
 }
 if(tag==='a')el.setAttribute('rel','noopener noreferrer');
 }
 return {html:doc.body.innerHTML,notes:[...new Set(notes)]};
}
export function audit(html){const doc=new DOMParser().parseFromString(html,'text/html'),issues=[];const imgs=[...doc.querySelectorAll('img,image')];const invalid=imgs.filter(i=>!isWechatImage(i.getAttribute('data-src')||i.getAttribute('src')||i.getAttribute('href')||i.getAttribute('xlink:href')||''));if(invalid.length)issues.push({level:'error',text:`${invalid.length} 张图片未使用微信素材地址，请先在公众号上传，再从正文读取。`});if(doc.querySelector('animate,animateTransform,animateMotion,set'))issues.push({level:'warn',text:'包含 SVG 动画：编辑器可能清理，需保存草稿后在手机预览确认。'});if(doc.querySelector('foreignObject'))issues.push({level:'warn',text:'包含 foreignObject 叠层：兼容性依赖微信版本与编辑器过滤。'});if([...doc.querySelectorAll('[style]')].some(e=>/overflow|perspective/.test(e.getAttribute('style'))))issues.push({level:'warn',text:'滑动与透视效果需在 iOS / Android 微信中分别检查。'});if(new Blob([html]).size>900000)issues.push({level:'error',text:'代码超过 900KB，请拆成更小的组件插入。'});if(!html.trim())issues.push({level:'error',text:'内容为空。'});return issues}
