import {catalog,build,cleanHTML,audit,escapeHTML,isWechatImage} from './engine.js';
export function mountPanel(root=document){
const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];let selected='horizontal',filter='全部',html='',music='',assets=[],nativeMusic=[],tab='components',busy=false;
const extension=false;
const message=async m=>extension?await chrome.runtime.sendMessage(m):({ok:false,error:'独立演示模式：安装扩展后即可连接公众号编辑器。'});
const status=t=>$('#status').textContent=t;
function params(){return Object.fromEntries(['title','body','accent','background','height','duration','radius','urls'].map(k=>[k,$('#'+k).value]).concat([['music',music],['custom',$('#code').value]]))}
function renderCatalog(){$('#catalog').innerHTML=catalog.filter(c=>c.id!=='custom'&&(filter==='全部'||c.group===filter)).map(c=>`<button class="component-card ${selected===c.id?'selected':''}" data-component="${c.id}"><i>${c.icon}</i><b>${c.name}</b><span>${c.level}</span></button>`).join('');$$('[data-component]').forEach(b=>b.onclick=()=>{selected=b.dataset.component;renderCatalog();update()})}
function preview(){const issues=audit(html);$('#checks').innerHTML=(issues.length?issues.map(i=>`<div class="check ${i.level}">${escapeHTML(i.text)}</div>`).join(''):'<div class="check ok">✓ 未发现阻止插入的素材问题</div>')+`<div class="check">${new Blob([html]).size.toLocaleString()} 字节 · 网页版 · 复制或下载后导入公众号</div>`;$('#insert').disabled=issues.some(i=>i.level==='error')||busy;const c=$('#background').value;$('#preview').srcdoc=`<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src https: data:; style-src 'unsafe-inline';"></head><body style="margin:0;background:${c};font-family:sans-serif;">${html}</body></html>`;$('#preview').style.width=$('#previewWidth').value+'px';$('#preview').style.height=Math.min(650,Math.max(220,Number($('#height').value)+90))+'px'}
function update(){const c=catalog.find(c=>c.id===selected);$('#componentName').textContent=c.name;$('#badge').textContent=c.level;$('#componentTip').textContent=c.desc;const urls=['horizontal','vertical','carousel','reveal','parallax'].includes(selected);$('#urlsField').hidden=!urls;$('#bodyField').hidden=!['neon','terminal','ticket','music'].includes(selected);const clean=cleanHTML(build(selected,params()));html=clean.html;$('#code').value=html;preview();persist()}
function persist(){if(!extension){try{localStorage.setItem('retro-paperplay-components',JSON.stringify({selected,params:params()}))}catch{}}if(extension)chrome.storage.local.set({panelSettings:{selected,params:params()}}).catch(()=>status('面板设置保存失败，可下载 HTML 备份'))}
function changeTab(t){tab=t;$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));for(const n of ['components','code','assets','backups'])$('#'+n+'Tab').hidden=t!==n;$('#config').hidden=t!=='components';$('#previewSection').hidden=['assets','backups'].includes(t);if(t==='backups')readBackups();if(t==='assets')readAssets()}
$$('[data-tab]').forEach(b=>b.onclick=()=>changeTab(b.dataset.tab));$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()});$$('#config input,#config textarea').forEach(e=>e.oninput=()=>{if(selected==='custom')selected='neon';update()});$('#previewWidth').onchange=preview;
$('#reset').onclick=()=>{$('#title').value='让声音，有迹可循。';$('#body').value='把瞬间收进纸间。\n把故事留给下一个听见它的人。';$('#height').value=360;$('#duration').value=4;$('#radius').value=0;$('#accent').value='#ccf58a';$('#background').value='#19251e';$('#urls').value='';music='';update()};
$('#applyCode').onclick=()=>{selected='custom';const clean=cleanHTML($('#code').value);html=clean.html;$('#code').value=html;preview();persist();status(clean.notes.length?'已清理：'+clean.notes.join('；'):'源码已更新，未发现需要移除的标签。')};
$('#code').oninput=()=>{html=cleanHTML($('#code').value).html;selected='custom';preview()};
function download(name,data,type='text/html'){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
$('#downloadCode').onclick=()=>download('paperplay-component.html',`<!doctype html><meta charset="utf-8">${html}`);
$('#copy').onclick=async()=>{try{const clean=cleanHTML(html);await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([clean.html],{type:'text/html'}),'text/plain':new Blob([clean.html],{type:'text/plain'})})]);status('排版已复制。在正文中定位光标后按 ⌘V / Ctrl+V。')}catch{try{await navigator.clipboard.writeText(html);status('已复制 HTML 源码。请使用支持源码导入的编辑器。')}catch{changeTab('code');$('#code').select();status('请按 ⌘C / Ctrl+C 复制所选源码。')}}};
$('#insert').onclick=async()=>{if(busy)return;busy=true;$('#insert').disabled=true;status('正在备份正文并插入…');try{html=cleanHTML(html).html;const r=await message({type:'INSERT',html,label:catalog.find(c=>c.id===selected)?.name||'自定义 HTML'});if(!r?.ok)throw Error(r?.error||'连接失败，请刷新公众号编辑页面');const a=new DOMParser().parseFromString(html,'text/html'),b=new DOMParser().parseFromString(r.after,'text/html'),before=new DOMParser().parseFromString(r.before,'text/html');const lost=['svg','animate','animateTransform','foreignObject','img'].filter(tag=>b.querySelectorAll(tag).length-before.querySelectorAll(tag).length<a.querySelectorAll(tag).length);status(lost.length?'已插入，但编辑器可能清理了 '+lost.join('、')+'。请检查正文；原文可在本机备份中恢复。':'已插入到正文，并保留操作前备份。请用公众号「预览」发到手机确认。')}catch(e){status(e.message)}finally{busy=false;preview()}};
async function refresh(){try{const r=await message({type:'READ'});$('#connection').textContent=r?.ok?`已连接正文 · ${r.chars} 字`:'未连接 · 可独立预览';if(!r?.ok)status('网页版组件库：调整参数后复制排版，或下载 HTML。')}catch{$('#connection').textContent='请刷新公众号编辑页';status('扩展已更新或页面尚未注入，请刷新公众号编辑页')}}
$('#refresh').onclick=refresh;$('#close').onclick=()=>message({type:'CLOSE'});
async function readAssets(){try{const r=await message({type:'READ'});if(!r?.ok)throw Error(r?.error);assets=r.images.filter(a=>isWechatImage(a.src));nativeMusic=r.music;$('#assets').innerHTML=assets.length?assets.map((a,i)=>`<label class="asset"><input type="checkbox" data-asset="${i}"><img src="${escapeHTML(a.src)}" alt="正文图片"><span>图片 ${i+1}<br>${escapeHTML(a.src.slice(0,65))}…</span></label>`).join(''):'<div class="empty">暂无微信图片。请先在正文上传图片。</div>';$('#musicAssets').innerHTML=nativeMusic.length?nativeMusic.map((m,i)=>`<button data-music="${i}">使用正文中的音乐卡片 ${i+1}</button>`).join(''):'<p class="hint">未找到原生音乐卡片。请在顶部「音频」中先插入。</p>';$$('[data-music]').forEach(b=>b.onclick=()=>{music=nativeMusic[Number(b.dataset.music)];selected='music';changeTab('components');renderCatalog();update();status('已读取原生音乐卡片。插入装饰版后可手动删除原卡片。')});status(`读取 ${assets.length} 张图片、${nativeMusic.length} 个音乐卡片。`)}catch(e){status(e.message)}}
$('#readAssets').onclick=readAssets;$('#useAssets').onclick=()=>{const chosen=$$('[data-asset]:checked').map(e=>assets[Number(e.dataset.asset)]);if(!chosen.length){status('请先勾选要使用的图片');return}$('#urls').value=chosen.map(a=>a.src).join('\n');if(!['horizontal','vertical','carousel','reveal','parallax'].includes(selected))selected='horizontal';changeTab('components');renderCatalog();update()};
function openStudio(){if(extension)message({type:'OPEN_STUDIO'}).then(r=>{if(!r?.ok)status(r?.error||'无法打开工作台')});else parent.postMessage({type:'paperplay-close-library'},location.origin)}
$('#studio').onclick=openStudio;$('#assetsToStudio').onclick=async()=>{const chosen=$$('[data-asset]:checked').map(e=>assets[Number(e.dataset.asset)]);if(!chosen.length){status('请先勾选图片');return}if(extension){await chrome.storage.local.set({studioAssets:chosen});openStudio()}};
async function readBackups(){try{const r=await message({type:'BACKUPS'});if(!r?.ok)throw Error(r?.error);$('#backups').innerHTML=r.backups.length?r.backups.map(b=>`<div class="backup"><b>${escapeHTML(b.label)}</b><small>${new Date(b.time).toLocaleString('zh-CN')} · ${b.pending?'插入前快照':'已完成'}</small><div class="row"><button data-download="${b.id}">下载备份</button><button data-undo="${b.id}" ${b.pending?'disabled':''}>撤销本次</button><button data-restore="${b.id}">整篇恢复</button></div></div>`).join(''):'<div class="empty">还没有操作备份。</div>';$$('[data-download]').forEach(b=>b.onclick=()=>download('paperplay-backup.html',r.backups.find(x=>x.id===b.dataset.download).before));$$('[data-undo],[data-restore]').forEach(b=>b.onclick=async()=>{const restore=!!b.dataset.restore;if(restore&&!confirm('将用这份备份替换当前整篇正文。当前正文会先另存为备份。确定恢复？'))return;b.disabled=true;try{const result=await message({type:restore?'RESTORE':'UNDO',id:b.dataset.restore||b.dataset.undo,label:restore?'恢复备份':'撤销插入'});status(result.ok?'正文已恢复。':result.error);await readBackups()}catch(e){status(e.message)}finally{b.disabled=false}})}catch(e){status(e.message)}}
$('#readBackups').onclick=readBackups;
async function init(){if(!extension){try{const saved=JSON.parse(localStorage.getItem('retro-paperplay-components'));if(saved&&catalog.some(c=>c.id===saved.selected)){selected=saved.selected;for(const [k,v] of Object.entries(saved.params||{}))if($('#'+k))$('#'+k).value=v;if(selected==='custom')$('#code').value=saved.params.custom||''}}catch{}}if(extension){const {panelSettings,studioExport}=await chrome.storage.local.get(['panelSettings','studioExport']);if(panelSettings&&catalog.some(c=>c.id===panelSettings.selected)){selected=panelSettings.selected;for(const [k,v]of Object.entries(panelSettings.params||{})){if($('#'+k))$('#'+k).value=v}music=panelSettings.params?.music||'';if(selected==='custom')$('#code').value=panelSettings.params?.custom||''}if(studioExport){selected='custom';$('#code').value=studioExport;await chrome.storage.local.remove('studioExport')}}renderCatalog();if(selected==='custom'){html=cleanHTML($('#code').value).html;preview()}else update();if(selected==='custom')changeTab('code');refresh()}init().catch(e=>{renderCatalog();update();status('设置恢复失败：'+e.message)});

if(extension)chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.studioExport?.newValue){selected='custom';html=cleanHTML(changes.studioExport.newValue).html;$('#code').value=html;changeTab('code');preview();status('收到底图工作台排版，检查后可插入正文。');chrome.storage.local.remove('studioExport')}});

}
if(document.querySelector('#catalog'))mountPanel();
