const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const limit=(v,a,b,d)=>Math.max(a,Math.min(b,Number.isFinite(Number(v))?Number(v):d));
export const isEffect=l=>['reveal','perspective','parallax'].includes(l.type);
export function normalizeEffect(l){l.images=Array.isArray(l.images)?l.images:[];l.effectDuration=limit(l.effectDuration,.1,10,.8);l.revealMode=['fade','up','left'].includes(l.revealMode)?l.revealMode:'fade';l.hint=String(l.hint??'点击揭开这一页');l.perspective=limit(l.perspective,100,2000,600);l.angle=limit(l.angle,-45,45,14);l.depth=limit(l.depth,0,1200,200);l.spacing=limit(l.spacing,0,500,48);l.travel=limit(l.travel,1.2,8,3);l.effectScale=limit(l.effectScale,.5,2,1);return l}
export function effectHTML(input,remote=false){const l=normalizeEffect({...input}),w=l.w,h=l.h;const source=a=>esc(remote?a.url:a.src);const picture=(a,label,style='')=>a?`<img alt="${esc(a.name)}" src="${source(a)}" draggable="false" style="display:block;width:100%;height:100%;object-fit:cover;${style}"/>`:`<section style="display:flex;align-items:center;justify-content:center;width:100%;height:100%;background:${label.includes('封面')?'#344332':'#718458'};color:#e0efc2;font:24px sans-serif;">${label}</section>`;
 if(l.type==='reveal'){
 const pic=(a,label)=>a?`<image width="${w}" height="${h}" href="${source(a)}" xlink:href="${source(a)}" preserveAspectRatio="xMidYMid slice"/>`:`<rect width="${w}" height="${h}" fill="${label==='封面'?'#344332':'#718458'}"/><text x="${w/2}" y="${h/2}" text-anchor="middle" fill="#d9ebbc" font-size="24">${label==='封面'?'上传封面':'揭幕后内容'}</text>`;
 const animation=l.revealMode==='fade'?`<animate attributeName="opacity" from="1" to="0" dur="${l.effectDuration}s" begin="click" fill="freeze" restart="never"/>`:`<animateTransform attributeName="transform" type="translate" from="0 0" to="${l.revealMode==='left'?-w:0} ${l.revealMode==='up'?-h:0}" dur="${l.effectDuration}s" begin="click" fill="freeze" restart="never"/>`;
 return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" style="display:block;width:100%;height:100%;overflow:hidden;" aria-label="点击揭幕"><g>${pic(l.images[1],'内容')}</g><g role="button" tabindex="0" aria-label="${esc(l.hint)}" style="cursor:pointer">${pic(l.images[0],'封面')}<rect y="${h-60}" width="${w}" height="60" fill="#000" opacity=".3"/><text x="${w/2}" y="${h-23}" text-anchor="middle" fill="#fff" font-family="sans-serif" font-size="18">${esc(l.hint)}</text>${animation}</g></svg>`;
 }
 const scroll=`width:${w}px;height:${h}px;overflow-x:hidden;overflow-y:auto;perspective:${l.perspective}px;perspective-origin:50% 50%;transform-style:preserve-3d;overscroll-behavior:contain;background:#182219;`;
 if(l.type==='perspective'){
 const images=l.images.length?l.images:[null,null,null];const cardH=h*.75,step=cardH+l.spacing;
 return `<section style="${scroll}" tabindex="0" aria-label="透视叠层，向下滚动"><section style="position:relative;transform-style:preserve-3d;min-height:${Math.max(h+1,images.length*step+l.spacing)}px;">${images.map((a,i)=>{const z=i%2?-l.depth:0;const compensation=(1-z/l.perspective)*l.effectScale;return `<section style="position:absolute;left:8%;top:${l.spacing+i*step}px;width:84%;height:${cardH}px;transform-origin:50% 50%;transform:translateZ(${z}px) rotateX(${i%2?l.angle:-l.angle}deg) scale(${compensation});box-shadow:0 16px 32px #0005;">${picture(a,`透视图层 ${i+1}`)}</section>`}).join('')}</section></section>`;
 }
 const length=h*l.travel,compensation=1+l.depth/l.perspective;
 return `<section style="${scroll}" tabindex="0" aria-label="长图视差，向下滚动"><section style="height:${length}px;position:relative;transform-style:preserve-3d;"><section style="position:absolute;inset:0;transform-origin:50% 0;transform:translateZ(${-l.depth}px) scale(${compensation});">${picture(l.images[0],'视差背景','object-fit:cover;')}</section><section style="position:relative;transform:translateZ(0);padding-top:${h*.6}px;">${(l.images.length>1?l.images.slice(1):[null,null]).map((a,i)=>`<section style="width:78%;height:${h*.65}px;margin:0 auto ${h*.5+l.spacing}px;">${picture(a,`前景 ${i+1}`)}</section>`).join('')}</section></section></section>`;
}
